import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div>{children}</div>
        <footer className="flex flex-col justify-end w-full p-8">
          <span className="self-center text-center text-white">
            Made with ❤️ by{" "}
            <Link
              className="underline"
              target="_blank"
              href="https://lev.engineer"
            >
              Lev Gelfenbuim
            </Link>
          </span>
        </footer>
      </body>
    </html>
  );
}
